USE airplanes_flights;

INSERT INTO flights (airplane_id, departure, airline_id, arrival, flight_id, flightno) VALUES (1, '2023-10-31 10:00:00', 123, '2023-10-31 12:00:00', 456, 'ABC123');
INSERT INTO flights (airplane_id, departure, airline_id, arrival, flight_id, flightno) VALUES (3, '2023-10-31 13:45:00', 456, '2023-10-31 16:30:00', 987, 'XYZ123');
INSERT INTO flights (airplane_id, departure, airline_id, arrival, flight_id, flightno) VALUES (5, '2023-10-31 14:15:00', 789, '2023-10-31 17:45:00', 654, 'ABC789');
INSERT INTO flights (airplane_id, departure, airline_id, arrival, flight_id, flightno) VALUES (4, '2023-10-31 16:30:00', 123, '2023-10-31 18:30:00', 753, 'XYZ456');
INSERT INTO flights (airplane_id, departure, airline_id, arrival, flight_id, flightno) VALUES (2, '2023-10-31 17:00:00', 456, '2023-10-31 20:15:00', 6543, 'ABC987');
INSERT INTO flights (airplane_id, departure, airline_id, arrival, flight_id, flightno) VALUES (4, '2023-10-31 18:30:00', 789, '2023-10-31 21:45:00', 7532, 'XYZ654');