USE airplanes_flights;

INSERT INTO airplanes(airline_id, capacity, airplane_id) VALUES (1, 100, 1);
INSERT INTO airplanes(airline_id, capacity, airplane_id) VALUES (1, 40, 2);
INSERT INTO airplanes(airline_id, capacity, airplane_id) VALUES (2, 221, 3);
INSERT INTO airplanes(airline_id, capacity, airplane_id) VALUES (2, 10, 4);
INSERT INTO airplanes(airline_id, capacity, airplane_id) VALUES (2, 145, 5);
INSERT INTO airplanes(airline_id, capacity, airplane_id) VALUES (2, 92, 6);
INSERT INTO airplanes(airline_id, capacity, airplane_id) VALUES (3, 70, 7);
INSERT INTO airplanes(airline_id, capacity, airplane_id) VALUES (3, 20, 8);